on:
  push:
    branches: main
  schedule:
    - cron: '00 00 * * *'

jobs:
  import-data:
    runs-on: ubuntu-latest
    outputs:
        NEW_DATA: ${{ steps.commit_results.new_data }}
    permissions:
      contents: write
    steps:
      - name: Set up R and enable P3M
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install dependencies
        run: |
          Rscript -e 'install.packages(c(
              "dplyr",
              "googlesheets4",
              "janitor",
              "purrr",
              "readr",
              "stringr",
              "tibble",
              "tidyr",
              "tidyselect",
              "usethis"
            ))'

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Import data
        run: Rscript -e 'source("data-raw/external-data.R")'
      - name: Refresh data
        run: Rscript -e 'source("data-raw/internal-data.R")'

      - name: Commit results
        id: commit_results
        run: |
          echo "new_data=true" >> "$GITHUB_OUTPUT"
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add 'data-raw/data.csv' 'R/sysdata.rda'
          git commit -m 'Data updated' || echo "No changes to commit"
          git push origin || echo "new_data=false" >> "$GITHUB_OUTPUT"
  deploy:
    needs: import-data
    runs-on: ubuntu-latest
    steps:
    - name: DigitalOcean App Platform deployment
      if: ${{ needs.import-data.outputs.new_data }}
      uses: digitalocean/app_action@v1.1.5
      with:
        app_name: climbwith
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
