on:
  push:
    branches: main
  schedule:
    - cron: '00 00 * * *'

jobs:
  import-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Enable P3M
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install dependencies
        run: |
          Rscript -e 'install.packages(c(
              "dplyr",
              "googlesheets4",
              "janitor",
              "purrr",
              "readr",
              "stringr",
              "tibble",
              "tidyr",
              "tidyselect",
              "usethis"
            ))'

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Import data
        run: Rscript -e 'source("data-raw/external-data.R")'
      - name: Refresh data
        run: Rscript -e 'source("data-raw/internal-data.R")'

      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add 'data-raw/data.csv' 'R/sysdata.rda'
          git commit -m 'Data updated' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Log in to DigitalOcean Container Registry with short-lived credentials
      run: doctl registry login --expiry-seconds 600

    - name: Deploy with doctl
      run: doctl apps create-deployment ${{ secrets.DIGITALOCEAN_APP_ID }}
